### ISSUE TITLE
How to add exceptions?

### ISSUE THREAD

**Issue by EdwardsMike** [kimryan/HumanNameParser#1]
Hi! I use Lingua::EN::NameParse quite a bit but lately have been running into having to deal with a mix of Asian and English names. Is there a way to add a list of exception cases so it will recognize things like "Yi", "Ni" and "An" as allowable names? I tried to do so in the code but my attempt failed. 

Thanks!

**Comment by kimryan** [comment]
Could you give a few examples. Not sure if Yi/Ni/An is given or surname.

**Comment by EdwardsMike** [comment]
Yes, it's hard to tell with some Chinese (other?) names since they often put the family/surname ahead of the individual's name. For my use, it doesn't matter so much as long as the name is parsed into first and last names. Here are just a few examples of what I'm dealing with. (I have more.) Most happen to be joint names.

YI FAN AND ANQI LI
MU NI AND YITING XIAO
XUEFEI DAI AND YI LI
BO ZHANG AND ADREY LIN
Jennifer and An Lien

**Comment by kimryan** [comment]
I've looked into it and found a bug. At line 627 in Grammar.pm, it should be:
my $given_name_min_2 = q{ given_name :/[A-Z]{2,} / | split_given_name  };
And in the new method, you need to set initials =>1 in the args.
Will release a patch soon to fix this. Thanks for spotting it.

**Comment by kimryan** [comment]
Sorry for the delay. Should be fixed now in version 1.37
